name: covid_api
description: Dart library to manage covid-19 api
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  build_runner: ^2.1.5
  equatable: ^2.0.3
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
